import { StyleSheet, Dimensions } from 'react-native';
import { SkibidiColors } from '../theme/SkibidiTheme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: SkibidiColors.darkChaos,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 20,
    color: SkibidiColors.textPrimary,
    fontWeight: '700',
  },
  fixedHeader: {
    backgroundColor: SkibidiColors.darkChaos,
    borderBottomWidth: 2,
    borderBottomColor: SkibidiColors.skibidiOrange,
    paddingVertical: 15,
    alignItems: 'center',
  },
  headerContent: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: SkibidiColors.textPrimary,
    textShadowColor: SkibidiColors.skibidiOrange,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  headerSubtitle: {
    fontSize: 14,
    color: SkibidiColors.textSecondary,
    fontWeight: '600',
    marginTop: 4,
  },
  headerUnderline: {
    width: 80,
    height: 2,
    backgroundColor: SkibidiColors.skibidiOrange,
    marginTop: 8,
    borderRadius: 1,
  },
  accountSelector: {
    backgroundColor: SkibidiColors.midChaos,
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SkibidiColors.skibidiOrange + '60',
  },
  accountButton: {
    padding: 12,
  },
  accountInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  accountEmoji: {
    fontSize: 18,
    marginRight: 8,
  },
  // accountName: {
  //   fontSize: 16,
  //   color: SkibidiColors.textPrimary,
  //   fontWeight: '700',
  //   flex: 1,
  // },
  accountDropdownIcon: {
    fontSize: 12,
    color: SkibidiColors.textMuted,
  },
  accountBalances: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  accountBalance: {
    fontSize: 12,
    color: SkibidiColors.crocodileGreen,
    fontWeight: '600',
  },
  accountOrdinals: {
    fontSize: 12,
    color: SkibidiColors.sigmaGold,
    fontWeight: '600',
  },
  contentArea: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  balanceCard: {
    backgroundColor: SkibidiColors.midChaos,
    padding: 24,
    borderRadius: 20,
    marginVertical: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: SkibidiColors.skibidiOrange,
    position: 'relative',
    overflow: 'hidden',
  },
  balanceHeader: {
    marginBottom: 12,
  },
  balanceLabel: {
    fontSize: 16,
    color: SkibidiColors.textMuted,
    fontWeight: '600',
  },
  balanceAmount: {
    fontSize: 32,
    fontWeight: '900',
    color: SkibidiColors.crocodileGreen,
    marginBottom: 8,
    textShadowColor: SkibidiColors.glowGreen,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  balanceSubtext: {
    fontSize: 14,
    color: SkibidiColors.sigmaGold,
    textAlign: 'center',
    fontWeight: '700',
  },
  balanceGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: SkibidiColors.glowOrange,
    opacity: 0.1,
    borderRadius: 20,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  actionButton: {
    flex: 1,
    marginHorizontal: 8,
  },
  messageCarousel: {
    alignItems: 'center',
    marginVertical: 20,
    paddingVertical: 16,
    backgroundColor: SkibidiColors.midChaos,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SkibidiColors.sigmaGold + '40',
  },
  messageContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  motivationText: {
    fontSize: 14,
    color: SkibidiColors.sigmaGold,
    textAlign: 'center',
    fontWeight: '700',
  },
  addressesContainer: {
    marginVertical: 20,
    padding: 16,
    backgroundColor: SkibidiColors.midChaos,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SkibidiColors.lightChaos,
  },
  addressesTitle: {
    fontSize: 16,
    color: SkibidiColors.textPrimary,
    fontWeight: '700',
    marginBottom: 12,
  },
  addressItem: {
    marginBottom: 12,
  },
  addressType: {
    fontSize: 12,
    color: SkibidiColors.textSecondary,
    fontWeight: '600',
    marginBottom: 4,
  },
  addressValue: {
    fontSize: 12,
    color: SkibidiColors.textMuted,
    fontFamily: 'monospace',
    backgroundColor: SkibidiColors.lightChaos,
    padding: 8,
    borderRadius: 6,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: SkibidiColors.midChaos,
    borderTopWidth: 2,
    borderTopColor: SkibidiColors.skibidiOrange,
    paddingVertical: 8,
  },
  navTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 8,
    marginHorizontal: 2,
  },
  navIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  navText: {
    fontSize: 10,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContent: {
    backgroundColor: SkibidiColors.midChaos,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: height * 0.8,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: SkibidiColors.lightChaos,
  },
  modalTitle: {
    fontSize: 20,
    color: SkibidiColors.textPrimary,
    fontWeight: '900',
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: 18,
    color: SkibidiColors.textMuted,
    fontWeight: '700',
  },
  accountsList: {
    maxHeight: height * 0.5,
    paddingHorizontal: 20,
  },
  accountItem: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 2,
  },
  accountItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  accountItemEmoji: {
    fontSize: 20,
    marginRight: 12,
  },
  accountItemName: {
    fontSize: 16,
    color: SkibidiColors.textPrimary,
    fontWeight: '700',
    flex: 1,
  },
  activeIndicator: {
    fontSize: 16,
    color: SkibidiColors.crocodileGreen,
    fontWeight: '900',
  },
  accountItemDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  accountItemBalance: {
    fontSize: 14,
    color: SkibidiColors.crocodileGreen,
    fontWeight: '600',
  },
  accountItemOrdinals: {
    fontSize: 14,
    color: SkibidiColors.sigmaGold,
    fontWeight: '600',
  },
  addressContainer: {
    backgroundColor: SkibidiColors.lightChaos,
    padding: 12,
    borderRadius: 8,
  },
  addressLabel: {
    fontSize: 10,
    color: SkibidiColors.textSecondary,
    fontWeight: '600',
    marginBottom: 2,
  },
  addressText: {
    fontSize: 10,
    color: SkibidiColors.textMuted,
    fontFamily: 'monospace',
    marginBottom: 6,
  },
  modalActions: {
    padding: 20,
  },
  createModalContent: {
    backgroundColor: SkibidiColors.midChaos,
    margin: 20,
    borderRadius: 16,
    padding: 20,
  },
  inputLabel: {
    fontSize: 14,
    color: SkibidiColors.textPrimary,
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 16,
  },
  textInput: {
    backgroundColor: SkibidiColors.lightChaos,
    borderRadius: 8,
    padding: 12,
    color: SkibidiColors.textPrimary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: SkibidiColors.skibidiOrange + '60',
  },
  emojiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  emojiButton: {
    width: (width - 120) / 5,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginBottom: 8,
  },
  emojiText: {
    fontSize: 20,
  },
  createModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  createActionButton: {
    flex: 1,
    marginHorizontal: 8,
  },
  placeholderContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  placeholderEmoji: {
    fontSize: 60,
    marginBottom: 20,
  },
  placeholderTitle: {
    fontSize: 24,
    color: SkibidiColors.textPrimary,
    fontWeight: '900',
    marginBottom: 16,
    textAlign: 'center',
  },
  placeholderText: {
    fontSize: 16,
    color: SkibidiColors.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
  },
  buttonInner: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: SkibidiColors.textPrimary,
    fontWeight: '800',
    textAlign: 'center',
  },
  particleContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  particle: {
    position: 'absolute',
    fontSize: 16,
  },
  onboardingContainer: {
    flex: 1,
    backgroundColor: SkibidiColors.darkChaos,
    justifyContent: 'center',
    alignItems: 'center',
  },
  onboardingContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  onboardingTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: SkibidiColors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: SkibidiColors.skibidiOrange,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  onboardingSubtitle: {
    fontSize: 18,
    color: SkibidiColors.textSecondary,
    textAlign: 'center',
    marginBottom: 40,
    fontWeight: '600',
  },
  subtitleText: {
    fontSize: 14,
    color: SkibidiColors.textSecondary,
    textAlign: 'center',
    fontWeight: '600',
  },
  onboardingDescription: {
    marginBottom: 60,
  },
  onboardingText: {
    fontSize: 16,
    color: SkibidiColors.textMuted,
    textAlign: 'center',
    lineHeight: 24,
  },
  onboardingButtons: {
    width: '100%',
    gap: 20,
    marginBottom: 40,
  },
  onboardingButton: {
    width: '100%',
  },
  onboardingWarning: {
    fontSize: 12,
    color: SkibidiColors.chaosRed,
    textAlign: 'center',
    fontWeight: '600',
  },
  importModalContent: {
    backgroundColor: SkibidiColors.midChaos,
    margin: 20,
    borderRadius: 16,
    padding: 20,
    flexGrow: 1,
  },
  privateKeyInput: {
    minHeight: 80,
    textAlignVertical: 'top',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  privateKeyHint: {
    fontSize: 12,
    color: SkibidiColors.textSecondary,
    marginTop: 8,
    marginBottom: 16,
    textAlign: 'center',
  },
  exportModalContent: {
    backgroundColor: SkibidiColors.midChaos,
    margin: 20,
    borderRadius: 16,
    padding: 20,
    maxHeight: height * 0.8,
  },
  accountExportEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  accountExportName: {
    fontSize: 18,
    color: SkibidiColors.textPrimary,
    fontWeight: '700',
  },
  exportWarning: {
    fontSize: 14,
    color: SkibidiColors.chaosRed,
    textAlign: 'center',
    marginVertical: 20,
    fontWeight: '600',
    lineHeight: 20,
  },
  privateKeyContainer: {
    marginVertical: 20,
  },
  hiddenKey: {
    fontSize: 12,
    color: SkibidiColors.textMuted,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'monospace',
  },
  privateKeyBox: {
    backgroundColor: SkibidiColors.lightChaos,
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: SkibidiColors.chaosRed + '40',
  },
  privateKeyText: {
    fontSize: 12,
    color: SkibidiColors.textPrimary,
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  revealButton: {
    marginTop: 10,
  },
  copyButton: {
    marginTop: 10,
  },
  errorText: {
    fontSize: 14,
    color: SkibidiColors.chaosRed,
    textAlign: 'center',
    marginVertical: 20,
  },
  exportButtonContainer: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  exportButton: {
    width: '100%',
  },
  accountNameContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  lightningStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  lightningIcon: {
    fontSize: 12,
    marginRight: 4,
    fontWeight: 'bold',
  },
  lightningStatusText: {
    fontSize: 10,
    color: '#888888',
    fontWeight: '500',
  },
  lightningBadge: {
    fontSize: 10,
    color: '#FFD700',
    fontWeight: '600',
    marginTop: 2,
  },
  accountName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 0, // Reduced to make room for lightning status
  },
  connectionStatus: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    marginHorizontal: 20,
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  connectionStatusText: {
    fontSize: 14,
    fontWeight: '600',
  },
  connectionSubtext: {
    fontSize: 12,
    color: '#888888',
    marginTop: 2,
  },
  quickStats: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  quickStatsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFD700',
    marginBottom: 12,
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 12,
    color: '#888888',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  
  // GameContent Styles
  gameStatusBar: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    marginHorizontal: 20,
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  gameStatusText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFD700',
    textAlign: 'center',
  },
  gameStatusSubtext: {
    fontSize: 12,
    color: '#888888',
    textAlign: 'center',
    marginTop: 2,
  },
  
  // TransactionsContent Styles
  transactionHeader: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    marginHorizontal: 20,
    marginTop: 10,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#FFD700',
  },
  transactionHeaderTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  transactionHeaderSubtitle: {
    fontSize: 14,
    color: '#888888',
    textAlign: 'center',
    marginTop: 4,
  },
  balanceSummary: {
    backgroundColor: 'rgba(0, 255, 136, 0.1)',
    marginHorizontal: 20,
    marginTop: 10,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 136, 0.3)',
    alignItems: 'center',
  },
  balanceSummaryTitle: {
    fontSize: 14,
    color: '#888888',
    marginBottom: 4,
  },
  balanceSummaryAmount: {
    fontSize: 24,
    fontWeight: '800',
    color: '#00FF88',
  },
  pendingContainer: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 8,
  },
  pendingReceive: {
    fontSize: 12,
    color: '#00FF88',
    fontWeight: '600',
  },
  pendingSend: {
    fontSize: 12,
    color: '#FF6B6B',
    fontWeight: '600',
  },
  // loadingContainer: {
  //   padding: 40,
  //   alignItems: 'center',
  // },
  // loadingText: {
  //   fontSize: 16,
  //   color: '#888888',
  //   fontWeight: '600',
  // },
  transactionsList: {
    marginHorizontal: 20,
    marginTop: 10,
  },
  transactionItem: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    marginBottom: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  transactionIcon: {
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionTypeIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  transactionStatusIcon: {
    fontSize: 12,
  },
  transactionDetails: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  transactionDescription: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  transactionDate: {
    fontSize: 12,
    color: '#888888',
    marginBottom: 2,
  },
  transactionDestination: {
    fontSize: 11,
    color: '#666666',
  },
  transactionAmount: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    minWidth: 80,
  },
  transactionAmountText: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 2,
  },
  transactionFees: {
    fontSize: 11,
    color: '#888888',
    marginBottom: 2,
  },
  transactionStatus: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  retryButton: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFD700',
    marginTop: 16,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFD700',
    textAlign: 'center',
  },
}); 